HEADER_APAC_2025 = [
    {"name": "identificador", "start": 1, "length": 2, "default": "01"},
    {"name": "marcador", "start": 3, "length": 5, "default": "#APAC"},
    {"name": "competencia", "start": 8, "length": 6, "required": True},
    {"name": "quantidade_apac", "start": 14, "length": 6, "required": True, "pad": "0"},
    {"name": "checksum", "start": 20, "length": 4, "required": True, "pad": "0"},
    {"name": "orgao", "start": 24, "length": 30, "required": True},
    {"name": "sigla", "start": 54, "length": 6, "required": True},
    {"name": "cnpj", "start": 60, "length": 14, "required": True},
    {"name": "destino", "start": 74, "length": 40, "required": True},
    {"name": "em", "start": 114, "length": 1, "required": True, "default": "E"},  # indicador emissao/recepcao
    {"name": "data_geracao", "start": 115, "length": 8, "required": True, "pad": "0"},
    {"name": "versao", "start": 123, "length": 15, "required": True},
]

CORPO_APAC_2025 = [
    {"name": "identificador", "start": 1, "length": 2, "default": "14"},
    {"name": "competencia", "start": 3, "length": 6, "required": True},
    {"name": "numero_apac", "start": 9, "length": 13, "required": True},
    {"name": "uf", "start": 22, "length": 2, "required": True},
    {"name": "cnes", "start": 24, "length": 7, "required": True},
    {"name": "data_processamento", "start": 31, "length": 8, "required": True, "pad": "0"},
    {"name": "data_inicio_validade", "start": 39, "length": 8, "required": True, "pad": "0"},
    {"name": "data_fim_validade", "start": 47, "length": 8, "required": True, "pad": "0"},
    {"name": "tipo_atendimento", "start": 55, "length": 2, "required": True, "pad": "0"},
    {"name": "tipo_apac", "start": 57, "length": 1, "required": True, "pad": "0"},
    {"name": "nome_paciente", "start": 58, "length": 30, "required": True},
    {"name": "nome_mae", "start": 88, "length": 30, "required": True},
    {"name": "logradouro", "start": 118, "length": 30, "required": True},
    {"name": "numero_endereco", "start": 148, "length": 5, "required": True, "pad": "0"},
    {"name": "complemento", "start": 153, "length": 10, "required": False},
    {"name": "cep", "start": 163, "length": 8, "required": True, "pad": "0"},
    {"name": "municipio_ibge", "start": 171, "length": 7, "required": True, "pad": "0"},
    {"name": "data_nascimento", "start": 178, "length": 8, "required": True, "pad": "0"},
    {"name": "sexo", "start": 186, "length": 1, "required": True},
    {"name": "nome_medico_responsavel", "start": 187, "length": 30, "required": True},
    {"name": "procedimento_principal", "start": 217, "length": 10, "required": True},
    {"name": "motivo_saida", "start": 227, "length": 2, "required": True, "pad": "0"},
    {"name": "data_obito_alta", "start": 229, "length": 8, "required": False, "pad": "0"},
    {"name": "nome_autorizador", "start": 237, "length": 30, "required": True},
    {"name": "cns_paciente", "start": 267, "length": 15, "required": True},
    {"name": "cns_medico_resp", "start": 282, "length": 15, "required": True},
    {"name": "cns_autorizador", "start": 297, "length": 15, "required": True},
    {"name": "cid_associado", "start": 312, "length": 4, "required": False},
    {"name": "num_prontuario", "start": 316, "length": 10, "required": False},
    {"name": "cnes_solicitante", "start": 326, "length": 7, "required": False, "pad": "0"},
    {"name": "data_solicitacao", "start": 333, "length": 8, "required": True, "pad": "0"},
    {"name": "data_autorizacao", "start": 341, "length": 8, "required": True, "pad": "0"},
    {"name": "codigo_emissor", "start": 349, "length": 10, "required": True},
    {"name": "carater_atendimento", "start": 359, "length": 2, "required": True},
    {"name": "apac_anterior", "start": 361, "length": 13, "required": False},
    {"name": "raca_cor", "start": 374, "length": 2, "required": True},
    {"name": "nome_responsavel", "start": 376, "length": 30, "required": True},
    {"name": "nacionalidade", "start": 406, "length": 3, "required": True},
    {"name": "etnia", "start": 409, "length": 4, "required": False},
    {"name": "cod_logradouro_ibge", "start": 413, "length": 3, "required": True},
    {"name": "bairro", "start": 416, "length": 30, "required": True},
    {"name": "ddd", "start": 446, "length": 2, "required": False},
    {"name": "fone", "start": 448, "length": 9, "required": False},
    {"name": "email", "start": 457, "length": 40, "required": False},
    {"name": "cns_executor", "start": 497, "length": 15, "required": True},
    {"name": "cpf_paciente", "start": 512, "length": 11, "required": False, "pad": "0"},
    {"name": "ine", "start": 523, "length": 10, "required": False},
    {"name": "pessoa_rua", "start": 533, "length": 1, "required": False},
    {"name": "fonte_orc", "start": 534, "length": 2, "required": False},
    {"name": "emenda", "start": 536, "length": 1, "required": False},
    # registro 14 deve terminar com filler + CRLF; CRLF garantido no exportador
    {"name": "fim", "start": 537, "length": 2, "required": False, "default": "  "},
]

PROC_APAC_2025 = [
    {"name": "identificador", "start": 1, "length": 2, "default": "13"},
    {"name": "competencia", "start": 3, "length": 6, "required": True},
    {"name": "numero_apac", "start": 9, "length": 13, "required": True},
    {"name": "codigo", "start": 22, "length": 10, "required": True},
    {"name": "cbo", "start": 32, "length": 6, "required": True, "default": "000000"},
    {"name": "quantidade", "start": 38, "length": 7, "required": True, "pad": "0"},
]
